### simple nested
GET http://localhost:8080/simple_nested/aaa

### multiple nesting level

GET http://localhost:8080/multi/top
###
GET http://localhost:8080/multi/multi_nested_level1/aaa
###
GET http://localhost:8080/multi/multi_nested_level1/zzz
###
GET http://localhost:8080/multi/multi_nested_level2/multi_nested_level21/bbb
###
GET http://localhost:8080/multi/multi_nested_level2/multi_nested_level21/ccc
###
GET http://localhost:8080/multi/multi_nested_level2/multi_nested_level22/ddd
###
GET http://localhost:8080/multi/multi_nested_level2/multi_nested_level22/eee
###


###   OR predicates:
GET http://localhost:8080/inline/alt/altinline_nested_level2/altinline_nested_level22/ddd2

###
GET http://localhost:8080/inline/alt/altinline_nested_level2/altinline_nested_level21/ccc1

###
GET http://localhost:8080/inline/alt/altinline_nested_level1/aaa2

### With predicates as local variables

###
GET http://localhost:8080/simple_nested_with_vars/foo

###
GET http://localhost:8080/simple_nested_with_vars/bar

###
GET http://localhost:8080/with_vars/bbb

###
GET http://localhost:8080/with_vars/complexnested_nested_level1/ccc

###
GET http://localhost:8080/with_vars/complexnested_nested_level1/fff

###
GET http://localhost:8080/with_vars/complexnested_nested_level1/complexnested_nested_level2/ggg
